[package]
name = "game_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
tinyvec = "1.6.0"
arrayvec = "0.7.4"
